#!/usr/bin/env bash
# Install your load balancer

# Update the package list
sudo apt update

# Install HAProxy
sudo apt install -y haproxy

# Get the hostname of the lb-01 server
hostname_lb=$(hostname)

# Configure HAProxy
sudo bash -c "cat > /etc/haproxy/haproxy.cfg <<EOL
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats

    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOL"

# Enable HAProxy to be managed via init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy to apply the changes
sudo service haproxy restart
